# Generated by Django 3.2.9 on 2021-11-26 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_folder_date_last_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='date_last_used',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
