# Generated by Django 3.2.9 on 2021-12-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_file_path',
        ),
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
